version: "3.6"

services:
# запуск ClearML. docker-compose из проекта clearml
# убедиться что сервис agent-services поднят

  clearml-worker:
    build:
      context: .
      dockerfile: Dockerfile.agent  
    # image: allegroai/clearml-agent:latest
    container_name: clearml-worker-detection
    restart: unless-stopped
    networks:
      - backend
      - front
    environment:
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8    
      - CLEARML_WORKER_NAME=clearml_worker_detection
      - CLEARML_AGENT_DEFAULT_BASE_DOCKER=python:3.11-slim
      - CLEARML_AGENT_QUEUES=default
      - CLEARML_AGENT_DAEMON_LOG_FILE=
      - CLEARML_API_ACCESS_KEY=N2QD8DEZBYCZWFZV3FXVB4QYIJPL68
      - CLEARML_API_SECRET_KEY=qfmHd_HXL5ed5mjkVKvyJjdnlEAnziHiZS7yV8L2gtgO3v8_J6cvohn6PryygEJbqrM
      - CLEARML_API_WEB_HOST=http://webserver:8080
      - CLEARML_API_HOST=http://apiserver:8008
      - CLEARML_API_FILES_HOST=http://fileserver:8081
    volumes:
      # - ./.clearml:/root/.clearml
      - /var/run/docker.sock:/var/run/docker.sock
      - clearml-pip-cache:/root/.cache/pip
      - clearml-apt-cache:/var/cache/apt/archives
      - clearml-vcs-cache:/root/.clearml/vcs-cache
    command: clearml-agent daemon --queue default  

volumes:
  clearml-pip-cache:
  clearml-apt-cache:
  clearml-vcs-cache:

networks:
  backend:
    external: true
    name: clearml_backend
  front:
    external: true
    name: clearml_frontend

