FROM python:3.8-slim

# Установка системных зависимостей (опционально)
# RUN apt-get update && apt-get install -y \
#     git \
#     && rm -rf /var/lib/apt/lists/*

# Установка pip нужной версии
RUN pip install --no-cache-dir pip==20.1.1

# Установка совместимых версий пакетов
RUN pip install --no-cache-dir \
    Cython==0.29.36 \
    clearml==1.17.0 \
    psutil==5.9.8 \
    urllib3==1.26.18 \
    requests==2.31.0 \
    numpy==1.24.4 \
    furl==2.1.3 \
    pathlib2==2.3.7.post1 \
    jsonschema==4.17.3 \
    PyYAML==6.0.2 \
    pyparsing==3.1.2 \
    Pillow==10.3.0 \
    six==1.16.0 \
    attrs==23.2.0 \
    python-dateutil==2.9.0.post0 \
    PyJWT==2.8.0 \
    idna==3.7 \
    charset-normalizer==3.3.2 \
    certifi==2024.7.4 \
    orderedmultidict==1.0.1 \
    importlib-metadata==6.7.0 \
    pyrsistent==0.20.0 \
    typing-extensions==4.12.2 \
    zipp==3.19.2

WORKDIR /workspace